// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Peas.proto

#ifndef PROTOBUF_INCLUDED_Peas_2eproto
#define PROTOBUF_INCLUDED_Peas_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Peas_2eproto 

namespace protobuf_Peas_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[10];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Peas_2eproto
namespace peas {
class AnKangPea;
class AnKangPeaDefaultTypeInternal;
extern AnKangPeaDefaultTypeInternal _AnKangPea_default_instance_;
class BeaPea;
class BeaPeaDefaultTypeInternal;
extern BeaPeaDefaultTypeInternal _BeaPea_default_instance_;
class BerimPea;
class BerimPeaDefaultTypeInternal;
extern BerimPeaDefaultTypeInternal _BerimPea_default_instance_;
class ChiPea;
class ChiPeaDefaultTypeInternal;
extern ChiPeaDefaultTypeInternal _ChiPea_default_instance_;
class FrontDoraOpen;
class FrontDoraOpenDefaultTypeInternal;
extern FrontDoraOpenDefaultTypeInternal _FrontDoraOpen_default_instance_;
class GaKangPea;
class GaKangPeaDefaultTypeInternal;
extern GaKangPeaDefaultTypeInternal _GaKangPea_default_instance_;
class GamePacket;
class GamePacketDefaultTypeInternal;
extern GamePacketDefaultTypeInternal _GamePacket_default_instance_;
class MingKangPea;
class MingKangPeaDefaultTypeInternal;
extern MingKangPeaDefaultTypeInternal _MingKangPea_default_instance_;
class PongPea;
class PongPeaDefaultTypeInternal;
extern PongPeaDefaultTypeInternal _PongPea_default_instance_;
class TsumoPea;
class TsumoPeaDefaultTypeInternal;
extern TsumoPeaDefaultTypeInternal _TsumoPea_default_instance_;
}  // namespace peas
namespace google {
namespace protobuf {
template<> ::peas::AnKangPea* Arena::CreateMaybeMessage<::peas::AnKangPea>(Arena*);
template<> ::peas::BeaPea* Arena::CreateMaybeMessage<::peas::BeaPea>(Arena*);
template<> ::peas::BerimPea* Arena::CreateMaybeMessage<::peas::BerimPea>(Arena*);
template<> ::peas::ChiPea* Arena::CreateMaybeMessage<::peas::ChiPea>(Arena*);
template<> ::peas::FrontDoraOpen* Arena::CreateMaybeMessage<::peas::FrontDoraOpen>(Arena*);
template<> ::peas::GaKangPea* Arena::CreateMaybeMessage<::peas::GaKangPea>(Arena*);
template<> ::peas::GamePacket* Arena::CreateMaybeMessage<::peas::GamePacket>(Arena*);
template<> ::peas::MingKangPea* Arena::CreateMaybeMessage<::peas::MingKangPea>(Arena*);
template<> ::peas::PongPea* Arena::CreateMaybeMessage<::peas::PongPea>(Arena*);
template<> ::peas::TsumoPea* Arena::CreateMaybeMessage<::peas::TsumoPea>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace peas {

// ===================================================================

class BeaPea : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peas.BeaPea) */ {
 public:
  BeaPea();
  virtual ~BeaPea();

  BeaPea(const BeaPea& from);

  inline BeaPea& operator=(const BeaPea& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BeaPea(BeaPea&& from) noexcept
    : BeaPea() {
    *this = ::std::move(from);
  }

  inline BeaPea& operator=(BeaPea&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BeaPea& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BeaPea* internal_default_instance() {
    return reinterpret_cast<const BeaPea*>(
               &_BeaPea_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BeaPea* other);
  friend void swap(BeaPea& a, BeaPea& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BeaPea* New() const final {
    return CreateMaybeMessage<BeaPea>(NULL);
  }

  BeaPea* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BeaPea>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BeaPea& from);
  void MergeFrom(const BeaPea& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BeaPea* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 sonpeas = 3;
  int sonpeas_size() const;
  void clear_sonpeas();
  static const int kSonpeasFieldNumber = 3;
  ::google::protobuf::int32 sonpeas(int index) const;
  void set_sonpeas(int index, ::google::protobuf::int32 value);
  void add_sonpeas(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      sonpeas() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_sonpeas();

  // int32 roomid = 1;
  void clear_roomid();
  static const int kRoomidFieldNumber = 1;
  ::google::protobuf::int32 roomid() const;
  void set_roomid(::google::protobuf::int32 value);

  // int32 jaksaindex = 2;
  void clear_jaksaindex();
  static const int kJaksaindexFieldNumber = 2;
  ::google::protobuf::int32 jaksaindex() const;
  void set_jaksaindex(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:peas.BeaPea)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > sonpeas_;
  mutable int _sonpeas_cached_byte_size_;
  ::google::protobuf::int32 roomid_;
  ::google::protobuf::int32 jaksaindex_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Peas_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TsumoPea : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peas.TsumoPea) */ {
 public:
  TsumoPea();
  virtual ~TsumoPea();

  TsumoPea(const TsumoPea& from);

  inline TsumoPea& operator=(const TsumoPea& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TsumoPea(TsumoPea&& from) noexcept
    : TsumoPea() {
    *this = ::std::move(from);
  }

  inline TsumoPea& operator=(TsumoPea&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TsumoPea& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TsumoPea* internal_default_instance() {
    return reinterpret_cast<const TsumoPea*>(
               &_TsumoPea_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(TsumoPea* other);
  friend void swap(TsumoPea& a, TsumoPea& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TsumoPea* New() const final {
    return CreateMaybeMessage<TsumoPea>(NULL);
  }

  TsumoPea* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TsumoPea>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TsumoPea& from);
  void MergeFrom(const TsumoPea& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TsumoPea* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 roomid = 1;
  void clear_roomid();
  static const int kRoomidFieldNumber = 1;
  ::google::protobuf::int32 roomid() const;
  void set_roomid(::google::protobuf::int32 value);

  // int32 jaksaindex = 2;
  void clear_jaksaindex();
  static const int kJaksaindexFieldNumber = 2;
  ::google::protobuf::int32 jaksaindex() const;
  void set_jaksaindex(::google::protobuf::int32 value);

  // int32 tileId = 3;
  void clear_tileid();
  static const int kTileIdFieldNumber = 3;
  ::google::protobuf::int32 tileid() const;
  void set_tileid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:peas.TsumoPea)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 roomid_;
  ::google::protobuf::int32 jaksaindex_;
  ::google::protobuf::int32 tileid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Peas_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BerimPea : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peas.BerimPea) */ {
 public:
  BerimPea();
  virtual ~BerimPea();

  BerimPea(const BerimPea& from);

  inline BerimPea& operator=(const BerimPea& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BerimPea(BerimPea&& from) noexcept
    : BerimPea() {
    *this = ::std::move(from);
  }

  inline BerimPea& operator=(BerimPea&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BerimPea& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BerimPea* internal_default_instance() {
    return reinterpret_cast<const BerimPea*>(
               &_BerimPea_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(BerimPea* other);
  friend void swap(BerimPea& a, BerimPea& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BerimPea* New() const final {
    return CreateMaybeMessage<BerimPea>(NULL);
  }

  BerimPea* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BerimPea>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BerimPea& from);
  void MergeFrom(const BerimPea& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BerimPea* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 roomid = 1;
  void clear_roomid();
  static const int kRoomidFieldNumber = 1;
  ::google::protobuf::int32 roomid() const;
  void set_roomid(::google::protobuf::int32 value);

  // int32 jaksaindex = 2;
  void clear_jaksaindex();
  static const int kJaksaindexFieldNumber = 2;
  ::google::protobuf::int32 jaksaindex() const;
  void set_jaksaindex(::google::protobuf::int32 value);

  // int32 tileId = 3;
  void clear_tileid();
  static const int kTileIdFieldNumber = 3;
  ::google::protobuf::int32 tileid() const;
  void set_tileid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:peas.BerimPea)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 roomid_;
  ::google::protobuf::int32 jaksaindex_;
  ::google::protobuf::int32 tileid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Peas_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ChiPea : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peas.ChiPea) */ {
 public:
  ChiPea();
  virtual ~ChiPea();

  ChiPea(const ChiPea& from);

  inline ChiPea& operator=(const ChiPea& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ChiPea(ChiPea&& from) noexcept
    : ChiPea() {
    *this = ::std::move(from);
  }

  inline ChiPea& operator=(ChiPea&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ChiPea& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ChiPea* internal_default_instance() {
    return reinterpret_cast<const ChiPea*>(
               &_ChiPea_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ChiPea* other);
  friend void swap(ChiPea& a, ChiPea& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ChiPea* New() const final {
    return CreateMaybeMessage<ChiPea>(NULL);
  }

  ChiPea* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ChiPea>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ChiPea& from);
  void MergeFrom(const ChiPea& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChiPea* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 huropea = 3;
  int huropea_size() const;
  void clear_huropea();
  static const int kHuropeaFieldNumber = 3;
  ::google::protobuf::int32 huropea(int index) const;
  void set_huropea(int index, ::google::protobuf::int32 value);
  void add_huropea(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      huropea() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_huropea();

  // int32 roomid = 1;
  void clear_roomid();
  static const int kRoomidFieldNumber = 1;
  ::google::protobuf::int32 roomid() const;
  void set_roomid(::google::protobuf::int32 value);

  // int32 jaksaindex = 2;
  void clear_jaksaindex();
  static const int kJaksaindexFieldNumber = 2;
  ::google::protobuf::int32 jaksaindex() const;
  void set_jaksaindex(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:peas.ChiPea)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > huropea_;
  mutable int _huropea_cached_byte_size_;
  ::google::protobuf::int32 roomid_;
  ::google::protobuf::int32 jaksaindex_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Peas_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PongPea : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peas.PongPea) */ {
 public:
  PongPea();
  virtual ~PongPea();

  PongPea(const PongPea& from);

  inline PongPea& operator=(const PongPea& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PongPea(PongPea&& from) noexcept
    : PongPea() {
    *this = ::std::move(from);
  }

  inline PongPea& operator=(PongPea&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PongPea& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PongPea* internal_default_instance() {
    return reinterpret_cast<const PongPea*>(
               &_PongPea_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(PongPea* other);
  friend void swap(PongPea& a, PongPea& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PongPea* New() const final {
    return CreateMaybeMessage<PongPea>(NULL);
  }

  PongPea* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PongPea>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PongPea& from);
  void MergeFrom(const PongPea& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PongPea* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 huropea = 3;
  int huropea_size() const;
  void clear_huropea();
  static const int kHuropeaFieldNumber = 3;
  ::google::protobuf::int32 huropea(int index) const;
  void set_huropea(int index, ::google::protobuf::int32 value);
  void add_huropea(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      huropea() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_huropea();

  // int32 roomid = 1;
  void clear_roomid();
  static const int kRoomidFieldNumber = 1;
  ::google::protobuf::int32 roomid() const;
  void set_roomid(::google::protobuf::int32 value);

  // int32 jaksaindex = 2;
  void clear_jaksaindex();
  static const int kJaksaindexFieldNumber = 2;
  ::google::protobuf::int32 jaksaindex() const;
  void set_jaksaindex(::google::protobuf::int32 value);

  // int32 index = 4;
  void clear_index();
  static const int kIndexFieldNumber = 4;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:peas.PongPea)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > huropea_;
  mutable int _huropea_cached_byte_size_;
  ::google::protobuf::int32 roomid_;
  ::google::protobuf::int32 jaksaindex_;
  ::google::protobuf::int32 index_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Peas_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MingKangPea : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peas.MingKangPea) */ {
 public:
  MingKangPea();
  virtual ~MingKangPea();

  MingKangPea(const MingKangPea& from);

  inline MingKangPea& operator=(const MingKangPea& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MingKangPea(MingKangPea&& from) noexcept
    : MingKangPea() {
    *this = ::std::move(from);
  }

  inline MingKangPea& operator=(MingKangPea&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MingKangPea& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MingKangPea* internal_default_instance() {
    return reinterpret_cast<const MingKangPea*>(
               &_MingKangPea_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(MingKangPea* other);
  friend void swap(MingKangPea& a, MingKangPea& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MingKangPea* New() const final {
    return CreateMaybeMessage<MingKangPea>(NULL);
  }

  MingKangPea* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MingKangPea>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MingKangPea& from);
  void MergeFrom(const MingKangPea& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MingKangPea* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 huropea = 3;
  int huropea_size() const;
  void clear_huropea();
  static const int kHuropeaFieldNumber = 3;
  ::google::protobuf::int32 huropea(int index) const;
  void set_huropea(int index, ::google::protobuf::int32 value);
  void add_huropea(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      huropea() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_huropea();

  // int32 roomid = 1;
  void clear_roomid();
  static const int kRoomidFieldNumber = 1;
  ::google::protobuf::int32 roomid() const;
  void set_roomid(::google::protobuf::int32 value);

  // int32 jaksaindex = 2;
  void clear_jaksaindex();
  static const int kJaksaindexFieldNumber = 2;
  ::google::protobuf::int32 jaksaindex() const;
  void set_jaksaindex(::google::protobuf::int32 value);

  // int32 index = 4;
  void clear_index();
  static const int kIndexFieldNumber = 4;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:peas.MingKangPea)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > huropea_;
  mutable int _huropea_cached_byte_size_;
  ::google::protobuf::int32 roomid_;
  ::google::protobuf::int32 jaksaindex_;
  ::google::protobuf::int32 index_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Peas_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GaKangPea : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peas.GaKangPea) */ {
 public:
  GaKangPea();
  virtual ~GaKangPea();

  GaKangPea(const GaKangPea& from);

  inline GaKangPea& operator=(const GaKangPea& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GaKangPea(GaKangPea&& from) noexcept
    : GaKangPea() {
    *this = ::std::move(from);
  }

  inline GaKangPea& operator=(GaKangPea&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GaKangPea& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GaKangPea* internal_default_instance() {
    return reinterpret_cast<const GaKangPea*>(
               &_GaKangPea_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(GaKangPea* other);
  friend void swap(GaKangPea& a, GaKangPea& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GaKangPea* New() const final {
    return CreateMaybeMessage<GaKangPea>(NULL);
  }

  GaKangPea* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GaKangPea>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GaKangPea& from);
  void MergeFrom(const GaKangPea& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GaKangPea* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 roomid = 1;
  void clear_roomid();
  static const int kRoomidFieldNumber = 1;
  ::google::protobuf::int32 roomid() const;
  void set_roomid(::google::protobuf::int32 value);

  // int32 jaksaindex = 2;
  void clear_jaksaindex();
  static const int kJaksaindexFieldNumber = 2;
  ::google::protobuf::int32 jaksaindex() const;
  void set_jaksaindex(::google::protobuf::int32 value);

  // int32 gaKangTile = 3;
  void clear_gakangtile();
  static const int kGaKangTileFieldNumber = 3;
  ::google::protobuf::int32 gakangtile() const;
  void set_gakangtile(::google::protobuf::int32 value);

  // int32 index = 4;
  void clear_index();
  static const int kIndexFieldNumber = 4;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:peas.GaKangPea)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 roomid_;
  ::google::protobuf::int32 jaksaindex_;
  ::google::protobuf::int32 gakangtile_;
  ::google::protobuf::int32 index_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Peas_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AnKangPea : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peas.AnKangPea) */ {
 public:
  AnKangPea();
  virtual ~AnKangPea();

  AnKangPea(const AnKangPea& from);

  inline AnKangPea& operator=(const AnKangPea& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AnKangPea(AnKangPea&& from) noexcept
    : AnKangPea() {
    *this = ::std::move(from);
  }

  inline AnKangPea& operator=(AnKangPea&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AnKangPea& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AnKangPea* internal_default_instance() {
    return reinterpret_cast<const AnKangPea*>(
               &_AnKangPea_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(AnKangPea* other);
  friend void swap(AnKangPea& a, AnKangPea& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AnKangPea* New() const final {
    return CreateMaybeMessage<AnKangPea>(NULL);
  }

  AnKangPea* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AnKangPea>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AnKangPea& from);
  void MergeFrom(const AnKangPea& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AnKangPea* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 huropea = 3;
  int huropea_size() const;
  void clear_huropea();
  static const int kHuropeaFieldNumber = 3;
  ::google::protobuf::int32 huropea(int index) const;
  void set_huropea(int index, ::google::protobuf::int32 value);
  void add_huropea(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      huropea() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_huropea();

  // int32 roomid = 1;
  void clear_roomid();
  static const int kRoomidFieldNumber = 1;
  ::google::protobuf::int32 roomid() const;
  void set_roomid(::google::protobuf::int32 value);

  // int32 jaksaindex = 2;
  void clear_jaksaindex();
  static const int kJaksaindexFieldNumber = 2;
  ::google::protobuf::int32 jaksaindex() const;
  void set_jaksaindex(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:peas.AnKangPea)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > huropea_;
  mutable int _huropea_cached_byte_size_;
  ::google::protobuf::int32 roomid_;
  ::google::protobuf::int32 jaksaindex_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Peas_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FrontDoraOpen : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peas.FrontDoraOpen) */ {
 public:
  FrontDoraOpen();
  virtual ~FrontDoraOpen();

  FrontDoraOpen(const FrontDoraOpen& from);

  inline FrontDoraOpen& operator=(const FrontDoraOpen& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FrontDoraOpen(FrontDoraOpen&& from) noexcept
    : FrontDoraOpen() {
    *this = ::std::move(from);
  }

  inline FrontDoraOpen& operator=(FrontDoraOpen&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrontDoraOpen& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FrontDoraOpen* internal_default_instance() {
    return reinterpret_cast<const FrontDoraOpen*>(
               &_FrontDoraOpen_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(FrontDoraOpen* other);
  friend void swap(FrontDoraOpen& a, FrontDoraOpen& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FrontDoraOpen* New() const final {
    return CreateMaybeMessage<FrontDoraOpen>(NULL);
  }

  FrontDoraOpen* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FrontDoraOpen>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FrontDoraOpen& from);
  void MergeFrom(const FrontDoraOpen& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrontDoraOpen* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 roomid = 1;
  void clear_roomid();
  static const int kRoomidFieldNumber = 1;
  ::google::protobuf::int32 roomid() const;
  void set_roomid(::google::protobuf::int32 value);

  // int32 tileId = 2;
  void clear_tileid();
  static const int kTileIdFieldNumber = 2;
  ::google::protobuf::int32 tileid() const;
  void set_tileid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:peas.FrontDoraOpen)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 roomid_;
  ::google::protobuf::int32 tileid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Peas_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GamePacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peas.GamePacket) */ {
 public:
  GamePacket();
  virtual ~GamePacket();

  GamePacket(const GamePacket& from);

  inline GamePacket& operator=(const GamePacket& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GamePacket(GamePacket&& from) noexcept
    : GamePacket() {
    *this = ::std::move(from);
  }

  inline GamePacket& operator=(GamePacket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GamePacket& default_instance();

  enum PayloadCase {
    kBeaPea = 1,
    kTsumoPea = 2,
    kBerimPea = 3,
    kChiPea = 4,
    kPongPea = 5,
    kMingKangPea = 6,
    kGaKangPea = 7,
    kAnKangPea = 8,
    kFrontDoraOpen = 9,
    PAYLOAD_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GamePacket* internal_default_instance() {
    return reinterpret_cast<const GamePacket*>(
               &_GamePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(GamePacket* other);
  friend void swap(GamePacket& a, GamePacket& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GamePacket* New() const final {
    return CreateMaybeMessage<GamePacket>(NULL);
  }

  GamePacket* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GamePacket>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GamePacket& from);
  void MergeFrom(const GamePacket& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GamePacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .peas.BeaPea bea_pea = 1;
  bool has_bea_pea() const;
  void clear_bea_pea();
  static const int kBeaPeaFieldNumber = 1;
  private:
  const ::peas::BeaPea& _internal_bea_pea() const;
  public:
  const ::peas::BeaPea& bea_pea() const;
  ::peas::BeaPea* release_bea_pea();
  ::peas::BeaPea* mutable_bea_pea();
  void set_allocated_bea_pea(::peas::BeaPea* bea_pea);

  // .peas.TsumoPea tsumo_pea = 2;
  bool has_tsumo_pea() const;
  void clear_tsumo_pea();
  static const int kTsumoPeaFieldNumber = 2;
  private:
  const ::peas::TsumoPea& _internal_tsumo_pea() const;
  public:
  const ::peas::TsumoPea& tsumo_pea() const;
  ::peas::TsumoPea* release_tsumo_pea();
  ::peas::TsumoPea* mutable_tsumo_pea();
  void set_allocated_tsumo_pea(::peas::TsumoPea* tsumo_pea);

  // .peas.BerimPea berim_pea = 3;
  bool has_berim_pea() const;
  void clear_berim_pea();
  static const int kBerimPeaFieldNumber = 3;
  private:
  const ::peas::BerimPea& _internal_berim_pea() const;
  public:
  const ::peas::BerimPea& berim_pea() const;
  ::peas::BerimPea* release_berim_pea();
  ::peas::BerimPea* mutable_berim_pea();
  void set_allocated_berim_pea(::peas::BerimPea* berim_pea);

  // .peas.ChiPea chi_pea = 4;
  bool has_chi_pea() const;
  void clear_chi_pea();
  static const int kChiPeaFieldNumber = 4;
  private:
  const ::peas::ChiPea& _internal_chi_pea() const;
  public:
  const ::peas::ChiPea& chi_pea() const;
  ::peas::ChiPea* release_chi_pea();
  ::peas::ChiPea* mutable_chi_pea();
  void set_allocated_chi_pea(::peas::ChiPea* chi_pea);

  // .peas.PongPea pong_pea = 5;
  bool has_pong_pea() const;
  void clear_pong_pea();
  static const int kPongPeaFieldNumber = 5;
  private:
  const ::peas::PongPea& _internal_pong_pea() const;
  public:
  const ::peas::PongPea& pong_pea() const;
  ::peas::PongPea* release_pong_pea();
  ::peas::PongPea* mutable_pong_pea();
  void set_allocated_pong_pea(::peas::PongPea* pong_pea);

  // .peas.MingKangPea ming_kang_pea = 6;
  bool has_ming_kang_pea() const;
  void clear_ming_kang_pea();
  static const int kMingKangPeaFieldNumber = 6;
  private:
  const ::peas::MingKangPea& _internal_ming_kang_pea() const;
  public:
  const ::peas::MingKangPea& ming_kang_pea() const;
  ::peas::MingKangPea* release_ming_kang_pea();
  ::peas::MingKangPea* mutable_ming_kang_pea();
  void set_allocated_ming_kang_pea(::peas::MingKangPea* ming_kang_pea);

  // .peas.GaKangPea ga_kang_pea = 7;
  bool has_ga_kang_pea() const;
  void clear_ga_kang_pea();
  static const int kGaKangPeaFieldNumber = 7;
  private:
  const ::peas::GaKangPea& _internal_ga_kang_pea() const;
  public:
  const ::peas::GaKangPea& ga_kang_pea() const;
  ::peas::GaKangPea* release_ga_kang_pea();
  ::peas::GaKangPea* mutable_ga_kang_pea();
  void set_allocated_ga_kang_pea(::peas::GaKangPea* ga_kang_pea);

  // .peas.AnKangPea an_kang_pea = 8;
  bool has_an_kang_pea() const;
  void clear_an_kang_pea();
  static const int kAnKangPeaFieldNumber = 8;
  private:
  const ::peas::AnKangPea& _internal_an_kang_pea() const;
  public:
  const ::peas::AnKangPea& an_kang_pea() const;
  ::peas::AnKangPea* release_an_kang_pea();
  ::peas::AnKangPea* mutable_an_kang_pea();
  void set_allocated_an_kang_pea(::peas::AnKangPea* an_kang_pea);

  // .peas.FrontDoraOpen front_dora_open = 9;
  bool has_front_dora_open() const;
  void clear_front_dora_open();
  static const int kFrontDoraOpenFieldNumber = 9;
  private:
  const ::peas::FrontDoraOpen& _internal_front_dora_open() const;
  public:
  const ::peas::FrontDoraOpen& front_dora_open() const;
  ::peas::FrontDoraOpen* release_front_dora_open();
  ::peas::FrontDoraOpen* mutable_front_dora_open();
  void set_allocated_front_dora_open(::peas::FrontDoraOpen* front_dora_open);

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:peas.GamePacket)
 private:
  void set_has_bea_pea();
  void set_has_tsumo_pea();
  void set_has_berim_pea();
  void set_has_chi_pea();
  void set_has_pong_pea();
  void set_has_ming_kang_pea();
  void set_has_ga_kang_pea();
  void set_has_an_kang_pea();
  void set_has_front_dora_open();

  inline bool has_payload() const;
  inline void clear_has_payload();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  union PayloadUnion {
    PayloadUnion() {}
    ::peas::BeaPea* bea_pea_;
    ::peas::TsumoPea* tsumo_pea_;
    ::peas::BerimPea* berim_pea_;
    ::peas::ChiPea* chi_pea_;
    ::peas::PongPea* pong_pea_;
    ::peas::MingKangPea* ming_kang_pea_;
    ::peas::GaKangPea* ga_kang_pea_;
    ::peas::AnKangPea* an_kang_pea_;
    ::peas::FrontDoraOpen* front_dora_open_;
  } payload_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_Peas_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BeaPea

// int32 roomid = 1;
inline void BeaPea::clear_roomid() {
  roomid_ = 0;
}
inline ::google::protobuf::int32 BeaPea::roomid() const {
  // @@protoc_insertion_point(field_get:peas.BeaPea.roomid)
  return roomid_;
}
inline void BeaPea::set_roomid(::google::protobuf::int32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:peas.BeaPea.roomid)
}

// int32 jaksaindex = 2;
inline void BeaPea::clear_jaksaindex() {
  jaksaindex_ = 0;
}
inline ::google::protobuf::int32 BeaPea::jaksaindex() const {
  // @@protoc_insertion_point(field_get:peas.BeaPea.jaksaindex)
  return jaksaindex_;
}
inline void BeaPea::set_jaksaindex(::google::protobuf::int32 value) {
  
  jaksaindex_ = value;
  // @@protoc_insertion_point(field_set:peas.BeaPea.jaksaindex)
}

// repeated int32 sonpeas = 3;
inline int BeaPea::sonpeas_size() const {
  return sonpeas_.size();
}
inline void BeaPea::clear_sonpeas() {
  sonpeas_.Clear();
}
inline ::google::protobuf::int32 BeaPea::sonpeas(int index) const {
  // @@protoc_insertion_point(field_get:peas.BeaPea.sonpeas)
  return sonpeas_.Get(index);
}
inline void BeaPea::set_sonpeas(int index, ::google::protobuf::int32 value) {
  sonpeas_.Set(index, value);
  // @@protoc_insertion_point(field_set:peas.BeaPea.sonpeas)
}
inline void BeaPea::add_sonpeas(::google::protobuf::int32 value) {
  sonpeas_.Add(value);
  // @@protoc_insertion_point(field_add:peas.BeaPea.sonpeas)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BeaPea::sonpeas() const {
  // @@protoc_insertion_point(field_list:peas.BeaPea.sonpeas)
  return sonpeas_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BeaPea::mutable_sonpeas() {
  // @@protoc_insertion_point(field_mutable_list:peas.BeaPea.sonpeas)
  return &sonpeas_;
}

// -------------------------------------------------------------------

// TsumoPea

// int32 roomid = 1;
inline void TsumoPea::clear_roomid() {
  roomid_ = 0;
}
inline ::google::protobuf::int32 TsumoPea::roomid() const {
  // @@protoc_insertion_point(field_get:peas.TsumoPea.roomid)
  return roomid_;
}
inline void TsumoPea::set_roomid(::google::protobuf::int32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:peas.TsumoPea.roomid)
}

// int32 jaksaindex = 2;
inline void TsumoPea::clear_jaksaindex() {
  jaksaindex_ = 0;
}
inline ::google::protobuf::int32 TsumoPea::jaksaindex() const {
  // @@protoc_insertion_point(field_get:peas.TsumoPea.jaksaindex)
  return jaksaindex_;
}
inline void TsumoPea::set_jaksaindex(::google::protobuf::int32 value) {
  
  jaksaindex_ = value;
  // @@protoc_insertion_point(field_set:peas.TsumoPea.jaksaindex)
}

// int32 tileId = 3;
inline void TsumoPea::clear_tileid() {
  tileid_ = 0;
}
inline ::google::protobuf::int32 TsumoPea::tileid() const {
  // @@protoc_insertion_point(field_get:peas.TsumoPea.tileId)
  return tileid_;
}
inline void TsumoPea::set_tileid(::google::protobuf::int32 value) {
  
  tileid_ = value;
  // @@protoc_insertion_point(field_set:peas.TsumoPea.tileId)
}

// -------------------------------------------------------------------

// BerimPea

// int32 roomid = 1;
inline void BerimPea::clear_roomid() {
  roomid_ = 0;
}
inline ::google::protobuf::int32 BerimPea::roomid() const {
  // @@protoc_insertion_point(field_get:peas.BerimPea.roomid)
  return roomid_;
}
inline void BerimPea::set_roomid(::google::protobuf::int32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:peas.BerimPea.roomid)
}

// int32 jaksaindex = 2;
inline void BerimPea::clear_jaksaindex() {
  jaksaindex_ = 0;
}
inline ::google::protobuf::int32 BerimPea::jaksaindex() const {
  // @@protoc_insertion_point(field_get:peas.BerimPea.jaksaindex)
  return jaksaindex_;
}
inline void BerimPea::set_jaksaindex(::google::protobuf::int32 value) {
  
  jaksaindex_ = value;
  // @@protoc_insertion_point(field_set:peas.BerimPea.jaksaindex)
}

// int32 tileId = 3;
inline void BerimPea::clear_tileid() {
  tileid_ = 0;
}
inline ::google::protobuf::int32 BerimPea::tileid() const {
  // @@protoc_insertion_point(field_get:peas.BerimPea.tileId)
  return tileid_;
}
inline void BerimPea::set_tileid(::google::protobuf::int32 value) {
  
  tileid_ = value;
  // @@protoc_insertion_point(field_set:peas.BerimPea.tileId)
}

// -------------------------------------------------------------------

// ChiPea

// int32 roomid = 1;
inline void ChiPea::clear_roomid() {
  roomid_ = 0;
}
inline ::google::protobuf::int32 ChiPea::roomid() const {
  // @@protoc_insertion_point(field_get:peas.ChiPea.roomid)
  return roomid_;
}
inline void ChiPea::set_roomid(::google::protobuf::int32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:peas.ChiPea.roomid)
}

// int32 jaksaindex = 2;
inline void ChiPea::clear_jaksaindex() {
  jaksaindex_ = 0;
}
inline ::google::protobuf::int32 ChiPea::jaksaindex() const {
  // @@protoc_insertion_point(field_get:peas.ChiPea.jaksaindex)
  return jaksaindex_;
}
inline void ChiPea::set_jaksaindex(::google::protobuf::int32 value) {
  
  jaksaindex_ = value;
  // @@protoc_insertion_point(field_set:peas.ChiPea.jaksaindex)
}

// repeated int32 huropea = 3;
inline int ChiPea::huropea_size() const {
  return huropea_.size();
}
inline void ChiPea::clear_huropea() {
  huropea_.Clear();
}
inline ::google::protobuf::int32 ChiPea::huropea(int index) const {
  // @@protoc_insertion_point(field_get:peas.ChiPea.huropea)
  return huropea_.Get(index);
}
inline void ChiPea::set_huropea(int index, ::google::protobuf::int32 value) {
  huropea_.Set(index, value);
  // @@protoc_insertion_point(field_set:peas.ChiPea.huropea)
}
inline void ChiPea::add_huropea(::google::protobuf::int32 value) {
  huropea_.Add(value);
  // @@protoc_insertion_point(field_add:peas.ChiPea.huropea)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ChiPea::huropea() const {
  // @@protoc_insertion_point(field_list:peas.ChiPea.huropea)
  return huropea_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ChiPea::mutable_huropea() {
  // @@protoc_insertion_point(field_mutable_list:peas.ChiPea.huropea)
  return &huropea_;
}

// -------------------------------------------------------------------

// PongPea

// int32 roomid = 1;
inline void PongPea::clear_roomid() {
  roomid_ = 0;
}
inline ::google::protobuf::int32 PongPea::roomid() const {
  // @@protoc_insertion_point(field_get:peas.PongPea.roomid)
  return roomid_;
}
inline void PongPea::set_roomid(::google::protobuf::int32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:peas.PongPea.roomid)
}

// int32 jaksaindex = 2;
inline void PongPea::clear_jaksaindex() {
  jaksaindex_ = 0;
}
inline ::google::protobuf::int32 PongPea::jaksaindex() const {
  // @@protoc_insertion_point(field_get:peas.PongPea.jaksaindex)
  return jaksaindex_;
}
inline void PongPea::set_jaksaindex(::google::protobuf::int32 value) {
  
  jaksaindex_ = value;
  // @@protoc_insertion_point(field_set:peas.PongPea.jaksaindex)
}

// repeated int32 huropea = 3;
inline int PongPea::huropea_size() const {
  return huropea_.size();
}
inline void PongPea::clear_huropea() {
  huropea_.Clear();
}
inline ::google::protobuf::int32 PongPea::huropea(int index) const {
  // @@protoc_insertion_point(field_get:peas.PongPea.huropea)
  return huropea_.Get(index);
}
inline void PongPea::set_huropea(int index, ::google::protobuf::int32 value) {
  huropea_.Set(index, value);
  // @@protoc_insertion_point(field_set:peas.PongPea.huropea)
}
inline void PongPea::add_huropea(::google::protobuf::int32 value) {
  huropea_.Add(value);
  // @@protoc_insertion_point(field_add:peas.PongPea.huropea)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PongPea::huropea() const {
  // @@protoc_insertion_point(field_list:peas.PongPea.huropea)
  return huropea_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PongPea::mutable_huropea() {
  // @@protoc_insertion_point(field_mutable_list:peas.PongPea.huropea)
  return &huropea_;
}

// int32 index = 4;
inline void PongPea::clear_index() {
  index_ = 0;
}
inline ::google::protobuf::int32 PongPea::index() const {
  // @@protoc_insertion_point(field_get:peas.PongPea.index)
  return index_;
}
inline void PongPea::set_index(::google::protobuf::int32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:peas.PongPea.index)
}

// -------------------------------------------------------------------

// MingKangPea

// int32 roomid = 1;
inline void MingKangPea::clear_roomid() {
  roomid_ = 0;
}
inline ::google::protobuf::int32 MingKangPea::roomid() const {
  // @@protoc_insertion_point(field_get:peas.MingKangPea.roomid)
  return roomid_;
}
inline void MingKangPea::set_roomid(::google::protobuf::int32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:peas.MingKangPea.roomid)
}

// int32 jaksaindex = 2;
inline void MingKangPea::clear_jaksaindex() {
  jaksaindex_ = 0;
}
inline ::google::protobuf::int32 MingKangPea::jaksaindex() const {
  // @@protoc_insertion_point(field_get:peas.MingKangPea.jaksaindex)
  return jaksaindex_;
}
inline void MingKangPea::set_jaksaindex(::google::protobuf::int32 value) {
  
  jaksaindex_ = value;
  // @@protoc_insertion_point(field_set:peas.MingKangPea.jaksaindex)
}

// repeated int32 huropea = 3;
inline int MingKangPea::huropea_size() const {
  return huropea_.size();
}
inline void MingKangPea::clear_huropea() {
  huropea_.Clear();
}
inline ::google::protobuf::int32 MingKangPea::huropea(int index) const {
  // @@protoc_insertion_point(field_get:peas.MingKangPea.huropea)
  return huropea_.Get(index);
}
inline void MingKangPea::set_huropea(int index, ::google::protobuf::int32 value) {
  huropea_.Set(index, value);
  // @@protoc_insertion_point(field_set:peas.MingKangPea.huropea)
}
inline void MingKangPea::add_huropea(::google::protobuf::int32 value) {
  huropea_.Add(value);
  // @@protoc_insertion_point(field_add:peas.MingKangPea.huropea)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
MingKangPea::huropea() const {
  // @@protoc_insertion_point(field_list:peas.MingKangPea.huropea)
  return huropea_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
MingKangPea::mutable_huropea() {
  // @@protoc_insertion_point(field_mutable_list:peas.MingKangPea.huropea)
  return &huropea_;
}

// int32 index = 4;
inline void MingKangPea::clear_index() {
  index_ = 0;
}
inline ::google::protobuf::int32 MingKangPea::index() const {
  // @@protoc_insertion_point(field_get:peas.MingKangPea.index)
  return index_;
}
inline void MingKangPea::set_index(::google::protobuf::int32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:peas.MingKangPea.index)
}

// -------------------------------------------------------------------

// GaKangPea

// int32 roomid = 1;
inline void GaKangPea::clear_roomid() {
  roomid_ = 0;
}
inline ::google::protobuf::int32 GaKangPea::roomid() const {
  // @@protoc_insertion_point(field_get:peas.GaKangPea.roomid)
  return roomid_;
}
inline void GaKangPea::set_roomid(::google::protobuf::int32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:peas.GaKangPea.roomid)
}

// int32 jaksaindex = 2;
inline void GaKangPea::clear_jaksaindex() {
  jaksaindex_ = 0;
}
inline ::google::protobuf::int32 GaKangPea::jaksaindex() const {
  // @@protoc_insertion_point(field_get:peas.GaKangPea.jaksaindex)
  return jaksaindex_;
}
inline void GaKangPea::set_jaksaindex(::google::protobuf::int32 value) {
  
  jaksaindex_ = value;
  // @@protoc_insertion_point(field_set:peas.GaKangPea.jaksaindex)
}

// int32 gaKangTile = 3;
inline void GaKangPea::clear_gakangtile() {
  gakangtile_ = 0;
}
inline ::google::protobuf::int32 GaKangPea::gakangtile() const {
  // @@protoc_insertion_point(field_get:peas.GaKangPea.gaKangTile)
  return gakangtile_;
}
inline void GaKangPea::set_gakangtile(::google::protobuf::int32 value) {
  
  gakangtile_ = value;
  // @@protoc_insertion_point(field_set:peas.GaKangPea.gaKangTile)
}

// int32 index = 4;
inline void GaKangPea::clear_index() {
  index_ = 0;
}
inline ::google::protobuf::int32 GaKangPea::index() const {
  // @@protoc_insertion_point(field_get:peas.GaKangPea.index)
  return index_;
}
inline void GaKangPea::set_index(::google::protobuf::int32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:peas.GaKangPea.index)
}

// -------------------------------------------------------------------

// AnKangPea

// int32 roomid = 1;
inline void AnKangPea::clear_roomid() {
  roomid_ = 0;
}
inline ::google::protobuf::int32 AnKangPea::roomid() const {
  // @@protoc_insertion_point(field_get:peas.AnKangPea.roomid)
  return roomid_;
}
inline void AnKangPea::set_roomid(::google::protobuf::int32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:peas.AnKangPea.roomid)
}

// int32 jaksaindex = 2;
inline void AnKangPea::clear_jaksaindex() {
  jaksaindex_ = 0;
}
inline ::google::protobuf::int32 AnKangPea::jaksaindex() const {
  // @@protoc_insertion_point(field_get:peas.AnKangPea.jaksaindex)
  return jaksaindex_;
}
inline void AnKangPea::set_jaksaindex(::google::protobuf::int32 value) {
  
  jaksaindex_ = value;
  // @@protoc_insertion_point(field_set:peas.AnKangPea.jaksaindex)
}

// repeated int32 huropea = 3;
inline int AnKangPea::huropea_size() const {
  return huropea_.size();
}
inline void AnKangPea::clear_huropea() {
  huropea_.Clear();
}
inline ::google::protobuf::int32 AnKangPea::huropea(int index) const {
  // @@protoc_insertion_point(field_get:peas.AnKangPea.huropea)
  return huropea_.Get(index);
}
inline void AnKangPea::set_huropea(int index, ::google::protobuf::int32 value) {
  huropea_.Set(index, value);
  // @@protoc_insertion_point(field_set:peas.AnKangPea.huropea)
}
inline void AnKangPea::add_huropea(::google::protobuf::int32 value) {
  huropea_.Add(value);
  // @@protoc_insertion_point(field_add:peas.AnKangPea.huropea)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
AnKangPea::huropea() const {
  // @@protoc_insertion_point(field_list:peas.AnKangPea.huropea)
  return huropea_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
AnKangPea::mutable_huropea() {
  // @@protoc_insertion_point(field_mutable_list:peas.AnKangPea.huropea)
  return &huropea_;
}

// -------------------------------------------------------------------

// FrontDoraOpen

// int32 roomid = 1;
inline void FrontDoraOpen::clear_roomid() {
  roomid_ = 0;
}
inline ::google::protobuf::int32 FrontDoraOpen::roomid() const {
  // @@protoc_insertion_point(field_get:peas.FrontDoraOpen.roomid)
  return roomid_;
}
inline void FrontDoraOpen::set_roomid(::google::protobuf::int32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:peas.FrontDoraOpen.roomid)
}

// int32 tileId = 2;
inline void FrontDoraOpen::clear_tileid() {
  tileid_ = 0;
}
inline ::google::protobuf::int32 FrontDoraOpen::tileid() const {
  // @@protoc_insertion_point(field_get:peas.FrontDoraOpen.tileId)
  return tileid_;
}
inline void FrontDoraOpen::set_tileid(::google::protobuf::int32 value) {
  
  tileid_ = value;
  // @@protoc_insertion_point(field_set:peas.FrontDoraOpen.tileId)
}

// -------------------------------------------------------------------

// GamePacket

// .peas.BeaPea bea_pea = 1;
inline bool GamePacket::has_bea_pea() const {
  return payload_case() == kBeaPea;
}
inline void GamePacket::set_has_bea_pea() {
  _oneof_case_[0] = kBeaPea;
}
inline void GamePacket::clear_bea_pea() {
  if (has_bea_pea()) {
    delete payload_.bea_pea_;
    clear_has_payload();
  }
}
inline const ::peas::BeaPea& GamePacket::_internal_bea_pea() const {
  return *payload_.bea_pea_;
}
inline ::peas::BeaPea* GamePacket::release_bea_pea() {
  // @@protoc_insertion_point(field_release:peas.GamePacket.bea_pea)
  if (has_bea_pea()) {
    clear_has_payload();
      ::peas::BeaPea* temp = payload_.bea_pea_;
    payload_.bea_pea_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::peas::BeaPea& GamePacket::bea_pea() const {
  // @@protoc_insertion_point(field_get:peas.GamePacket.bea_pea)
  return has_bea_pea()
      ? *payload_.bea_pea_
      : *reinterpret_cast< ::peas::BeaPea*>(&::peas::_BeaPea_default_instance_);
}
inline ::peas::BeaPea* GamePacket::mutable_bea_pea() {
  if (!has_bea_pea()) {
    clear_payload();
    set_has_bea_pea();
    payload_.bea_pea_ = CreateMaybeMessage< ::peas::BeaPea >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:peas.GamePacket.bea_pea)
  return payload_.bea_pea_;
}

// .peas.TsumoPea tsumo_pea = 2;
inline bool GamePacket::has_tsumo_pea() const {
  return payload_case() == kTsumoPea;
}
inline void GamePacket::set_has_tsumo_pea() {
  _oneof_case_[0] = kTsumoPea;
}
inline void GamePacket::clear_tsumo_pea() {
  if (has_tsumo_pea()) {
    delete payload_.tsumo_pea_;
    clear_has_payload();
  }
}
inline const ::peas::TsumoPea& GamePacket::_internal_tsumo_pea() const {
  return *payload_.tsumo_pea_;
}
inline ::peas::TsumoPea* GamePacket::release_tsumo_pea() {
  // @@protoc_insertion_point(field_release:peas.GamePacket.tsumo_pea)
  if (has_tsumo_pea()) {
    clear_has_payload();
      ::peas::TsumoPea* temp = payload_.tsumo_pea_;
    payload_.tsumo_pea_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::peas::TsumoPea& GamePacket::tsumo_pea() const {
  // @@protoc_insertion_point(field_get:peas.GamePacket.tsumo_pea)
  return has_tsumo_pea()
      ? *payload_.tsumo_pea_
      : *reinterpret_cast< ::peas::TsumoPea*>(&::peas::_TsumoPea_default_instance_);
}
inline ::peas::TsumoPea* GamePacket::mutable_tsumo_pea() {
  if (!has_tsumo_pea()) {
    clear_payload();
    set_has_tsumo_pea();
    payload_.tsumo_pea_ = CreateMaybeMessage< ::peas::TsumoPea >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:peas.GamePacket.tsumo_pea)
  return payload_.tsumo_pea_;
}

// .peas.BerimPea berim_pea = 3;
inline bool GamePacket::has_berim_pea() const {
  return payload_case() == kBerimPea;
}
inline void GamePacket::set_has_berim_pea() {
  _oneof_case_[0] = kBerimPea;
}
inline void GamePacket::clear_berim_pea() {
  if (has_berim_pea()) {
    delete payload_.berim_pea_;
    clear_has_payload();
  }
}
inline const ::peas::BerimPea& GamePacket::_internal_berim_pea() const {
  return *payload_.berim_pea_;
}
inline ::peas::BerimPea* GamePacket::release_berim_pea() {
  // @@protoc_insertion_point(field_release:peas.GamePacket.berim_pea)
  if (has_berim_pea()) {
    clear_has_payload();
      ::peas::BerimPea* temp = payload_.berim_pea_;
    payload_.berim_pea_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::peas::BerimPea& GamePacket::berim_pea() const {
  // @@protoc_insertion_point(field_get:peas.GamePacket.berim_pea)
  return has_berim_pea()
      ? *payload_.berim_pea_
      : *reinterpret_cast< ::peas::BerimPea*>(&::peas::_BerimPea_default_instance_);
}
inline ::peas::BerimPea* GamePacket::mutable_berim_pea() {
  if (!has_berim_pea()) {
    clear_payload();
    set_has_berim_pea();
    payload_.berim_pea_ = CreateMaybeMessage< ::peas::BerimPea >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:peas.GamePacket.berim_pea)
  return payload_.berim_pea_;
}

// .peas.ChiPea chi_pea = 4;
inline bool GamePacket::has_chi_pea() const {
  return payload_case() == kChiPea;
}
inline void GamePacket::set_has_chi_pea() {
  _oneof_case_[0] = kChiPea;
}
inline void GamePacket::clear_chi_pea() {
  if (has_chi_pea()) {
    delete payload_.chi_pea_;
    clear_has_payload();
  }
}
inline const ::peas::ChiPea& GamePacket::_internal_chi_pea() const {
  return *payload_.chi_pea_;
}
inline ::peas::ChiPea* GamePacket::release_chi_pea() {
  // @@protoc_insertion_point(field_release:peas.GamePacket.chi_pea)
  if (has_chi_pea()) {
    clear_has_payload();
      ::peas::ChiPea* temp = payload_.chi_pea_;
    payload_.chi_pea_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::peas::ChiPea& GamePacket::chi_pea() const {
  // @@protoc_insertion_point(field_get:peas.GamePacket.chi_pea)
  return has_chi_pea()
      ? *payload_.chi_pea_
      : *reinterpret_cast< ::peas::ChiPea*>(&::peas::_ChiPea_default_instance_);
}
inline ::peas::ChiPea* GamePacket::mutable_chi_pea() {
  if (!has_chi_pea()) {
    clear_payload();
    set_has_chi_pea();
    payload_.chi_pea_ = CreateMaybeMessage< ::peas::ChiPea >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:peas.GamePacket.chi_pea)
  return payload_.chi_pea_;
}

// .peas.PongPea pong_pea = 5;
inline bool GamePacket::has_pong_pea() const {
  return payload_case() == kPongPea;
}
inline void GamePacket::set_has_pong_pea() {
  _oneof_case_[0] = kPongPea;
}
inline void GamePacket::clear_pong_pea() {
  if (has_pong_pea()) {
    delete payload_.pong_pea_;
    clear_has_payload();
  }
}
inline const ::peas::PongPea& GamePacket::_internal_pong_pea() const {
  return *payload_.pong_pea_;
}
inline ::peas::PongPea* GamePacket::release_pong_pea() {
  // @@protoc_insertion_point(field_release:peas.GamePacket.pong_pea)
  if (has_pong_pea()) {
    clear_has_payload();
      ::peas::PongPea* temp = payload_.pong_pea_;
    payload_.pong_pea_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::peas::PongPea& GamePacket::pong_pea() const {
  // @@protoc_insertion_point(field_get:peas.GamePacket.pong_pea)
  return has_pong_pea()
      ? *payload_.pong_pea_
      : *reinterpret_cast< ::peas::PongPea*>(&::peas::_PongPea_default_instance_);
}
inline ::peas::PongPea* GamePacket::mutable_pong_pea() {
  if (!has_pong_pea()) {
    clear_payload();
    set_has_pong_pea();
    payload_.pong_pea_ = CreateMaybeMessage< ::peas::PongPea >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:peas.GamePacket.pong_pea)
  return payload_.pong_pea_;
}

// .peas.MingKangPea ming_kang_pea = 6;
inline bool GamePacket::has_ming_kang_pea() const {
  return payload_case() == kMingKangPea;
}
inline void GamePacket::set_has_ming_kang_pea() {
  _oneof_case_[0] = kMingKangPea;
}
inline void GamePacket::clear_ming_kang_pea() {
  if (has_ming_kang_pea()) {
    delete payload_.ming_kang_pea_;
    clear_has_payload();
  }
}
inline const ::peas::MingKangPea& GamePacket::_internal_ming_kang_pea() const {
  return *payload_.ming_kang_pea_;
}
inline ::peas::MingKangPea* GamePacket::release_ming_kang_pea() {
  // @@protoc_insertion_point(field_release:peas.GamePacket.ming_kang_pea)
  if (has_ming_kang_pea()) {
    clear_has_payload();
      ::peas::MingKangPea* temp = payload_.ming_kang_pea_;
    payload_.ming_kang_pea_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::peas::MingKangPea& GamePacket::ming_kang_pea() const {
  // @@protoc_insertion_point(field_get:peas.GamePacket.ming_kang_pea)
  return has_ming_kang_pea()
      ? *payload_.ming_kang_pea_
      : *reinterpret_cast< ::peas::MingKangPea*>(&::peas::_MingKangPea_default_instance_);
}
inline ::peas::MingKangPea* GamePacket::mutable_ming_kang_pea() {
  if (!has_ming_kang_pea()) {
    clear_payload();
    set_has_ming_kang_pea();
    payload_.ming_kang_pea_ = CreateMaybeMessage< ::peas::MingKangPea >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:peas.GamePacket.ming_kang_pea)
  return payload_.ming_kang_pea_;
}

// .peas.GaKangPea ga_kang_pea = 7;
inline bool GamePacket::has_ga_kang_pea() const {
  return payload_case() == kGaKangPea;
}
inline void GamePacket::set_has_ga_kang_pea() {
  _oneof_case_[0] = kGaKangPea;
}
inline void GamePacket::clear_ga_kang_pea() {
  if (has_ga_kang_pea()) {
    delete payload_.ga_kang_pea_;
    clear_has_payload();
  }
}
inline const ::peas::GaKangPea& GamePacket::_internal_ga_kang_pea() const {
  return *payload_.ga_kang_pea_;
}
inline ::peas::GaKangPea* GamePacket::release_ga_kang_pea() {
  // @@protoc_insertion_point(field_release:peas.GamePacket.ga_kang_pea)
  if (has_ga_kang_pea()) {
    clear_has_payload();
      ::peas::GaKangPea* temp = payload_.ga_kang_pea_;
    payload_.ga_kang_pea_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::peas::GaKangPea& GamePacket::ga_kang_pea() const {
  // @@protoc_insertion_point(field_get:peas.GamePacket.ga_kang_pea)
  return has_ga_kang_pea()
      ? *payload_.ga_kang_pea_
      : *reinterpret_cast< ::peas::GaKangPea*>(&::peas::_GaKangPea_default_instance_);
}
inline ::peas::GaKangPea* GamePacket::mutable_ga_kang_pea() {
  if (!has_ga_kang_pea()) {
    clear_payload();
    set_has_ga_kang_pea();
    payload_.ga_kang_pea_ = CreateMaybeMessage< ::peas::GaKangPea >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:peas.GamePacket.ga_kang_pea)
  return payload_.ga_kang_pea_;
}

// .peas.AnKangPea an_kang_pea = 8;
inline bool GamePacket::has_an_kang_pea() const {
  return payload_case() == kAnKangPea;
}
inline void GamePacket::set_has_an_kang_pea() {
  _oneof_case_[0] = kAnKangPea;
}
inline void GamePacket::clear_an_kang_pea() {
  if (has_an_kang_pea()) {
    delete payload_.an_kang_pea_;
    clear_has_payload();
  }
}
inline const ::peas::AnKangPea& GamePacket::_internal_an_kang_pea() const {
  return *payload_.an_kang_pea_;
}
inline ::peas::AnKangPea* GamePacket::release_an_kang_pea() {
  // @@protoc_insertion_point(field_release:peas.GamePacket.an_kang_pea)
  if (has_an_kang_pea()) {
    clear_has_payload();
      ::peas::AnKangPea* temp = payload_.an_kang_pea_;
    payload_.an_kang_pea_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::peas::AnKangPea& GamePacket::an_kang_pea() const {
  // @@protoc_insertion_point(field_get:peas.GamePacket.an_kang_pea)
  return has_an_kang_pea()
      ? *payload_.an_kang_pea_
      : *reinterpret_cast< ::peas::AnKangPea*>(&::peas::_AnKangPea_default_instance_);
}
inline ::peas::AnKangPea* GamePacket::mutable_an_kang_pea() {
  if (!has_an_kang_pea()) {
    clear_payload();
    set_has_an_kang_pea();
    payload_.an_kang_pea_ = CreateMaybeMessage< ::peas::AnKangPea >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:peas.GamePacket.an_kang_pea)
  return payload_.an_kang_pea_;
}

// .peas.FrontDoraOpen front_dora_open = 9;
inline bool GamePacket::has_front_dora_open() const {
  return payload_case() == kFrontDoraOpen;
}
inline void GamePacket::set_has_front_dora_open() {
  _oneof_case_[0] = kFrontDoraOpen;
}
inline void GamePacket::clear_front_dora_open() {
  if (has_front_dora_open()) {
    delete payload_.front_dora_open_;
    clear_has_payload();
  }
}
inline const ::peas::FrontDoraOpen& GamePacket::_internal_front_dora_open() const {
  return *payload_.front_dora_open_;
}
inline ::peas::FrontDoraOpen* GamePacket::release_front_dora_open() {
  // @@protoc_insertion_point(field_release:peas.GamePacket.front_dora_open)
  if (has_front_dora_open()) {
    clear_has_payload();
      ::peas::FrontDoraOpen* temp = payload_.front_dora_open_;
    payload_.front_dora_open_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::peas::FrontDoraOpen& GamePacket::front_dora_open() const {
  // @@protoc_insertion_point(field_get:peas.GamePacket.front_dora_open)
  return has_front_dora_open()
      ? *payload_.front_dora_open_
      : *reinterpret_cast< ::peas::FrontDoraOpen*>(&::peas::_FrontDoraOpen_default_instance_);
}
inline ::peas::FrontDoraOpen* GamePacket::mutable_front_dora_open() {
  if (!has_front_dora_open()) {
    clear_payload();
    set_has_front_dora_open();
    payload_.front_dora_open_ = CreateMaybeMessage< ::peas::FrontDoraOpen >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:peas.GamePacket.front_dora_open)
  return payload_.front_dora_open_;
}

inline bool GamePacket::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void GamePacket::clear_has_payload() {
  _oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline GamePacket::PayloadCase GamePacket::payload_case() const {
  return GamePacket::PayloadCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace peas

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Peas_2eproto
