#pragma once
#define HWARYO_CHECKER_DEBUG
#define HWARYO_INFO_DEBUG
#define HWARYO_CHECK_SONPAE_DEBUG
#define HWARYO_HURO_ANKEO_INFO_DEBUG
#define TSU_BLOCK_DEBUG

#define YAKU_CHECKER_DEBUG
#define YAKU_CHANTANODU_DEBUG
#define YAKU_CHITOI_DEBUG
#define YAKU_COLORS_DEBUG
#define YAKU_DORA_DEBUG
#define YAKU_DRAGON_DEBUG
#define YAKU_GUKSA_DEBUG
#define YAKU_ILGI_DEBUG
#define YAKU_INFO_DEBUG
#define YAKU_PANSU_DEBUG
#define YAKU_PEKO_DEBUG
#define YAKU_PINGHU_DEBUG
#define YAKU_RICHI_ILBAL_DEBUG
#define YAKU_SAMDONG_DEBUG
#define YAKU_SUSHI_DEBUG
#define YAKU_TANYAO_DEBUG
#define YAKU_TOITOI_ANKEO_DEBUG
#define YAKU_TSUMO_RON_DEP_DEBUG
#define YAKU_WIND_DEBUG


#define TENPAI_CHITOI_DEBUG
#define TENPAI_GUKSA_DEBUG
#define TENPAI_SONPAE_CHECK_DEBUG
#define TENPAI_CHECKER_DEBUG
#define TENPAI_CHECKER_ASSIST_DEBUG
#define TENPAI_INFO_DEBUG
#define TENPAI_CHECKER_DEBUG

